apiVersion: apps/v1
kind: Deployment
metadata:
  name: aib-api
  namespace: ztr-aa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aib-api
  template:
    metadata:
      labels:
        app: aib-api
    spec:
      containers:
        - name: aib-api
          image: aib-api:local
          ports:
            - containerPort: 8080
          env:
            - name: AIB_OPA_URL
              value: "http://opa:8181"
            - name: AIB_JWT_ISSUER
              value: "aib.local"
            - name: AIB_JWT_AUDIENCE
              value: "ztr-aa"
            - name: AIB_JWT_TTL_SECONDS
              value: "300"
            - name: AIB_SIGNING_KEY_DEV_ONLY
              valueFrom:
                secretKeyRef:
                  name: aib-signing-key
                  key: key
